branch-defaults:
  Sprint4:
    environment: null
    group_suffix: null
global:
  application_name: animaloutcomes
  branch: null
  default_ec2_keyname: flaskpair
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
