from flask_wtf import FlaskForm
from wtforms import SelectField, RadioField, StringField, DecimalField, BooleanField, SubmitField, IntegerField
from wtforms.validators import DataRequired


# Create user form
class DataForm(FlaskForm):
	gender = SelectField('Gender of animal:', choices=[('Male','Male'), ('Female','Female'), ('Unknown','Unknown')])
	hasName = RadioField('Does the animal have a name?', choices=[('1','Yes'), ('0','No')])
	ageWeeks = IntegerField('Age in weeks:', validators=[DataRequired()])
	animal = SelectField('Type of animal:', choices=[('1','Dog'),('0','Cat')])
	isMix = RadioField('Is the animal a mix?', choices=[('1','Yes'), ('0','No')])
	month = SelectField('Month brought to shelter:', choices=[('1','Jan'),('2','Feb'),('3','Mar'),('4','Apr'),('5','May'),('6','June'),('7','Jul'),('8','Aug'),('9','Sep'),('10','Oct'),('11','Nov'),('12','Dec')])
	weekday = SelectField('Day of week brought to shelter:', choices=[('Sunday','Sunday'),('Monday','Monday'),('Tuesday','Tuesday'),('Wednesday','Wednesday'),('Thursday','Thursday'),('Friday','Friday'),('Saturday','Saturday')])
	hourOfDay = SelectField('Hour of day brought to shelter:', choices=[('0','12am'),('1','1am'),('2','2am'),('3','3am'),('4','4am'),('5','5am'),('6','6am'),('7','7am'),('8','8am'),('9','9am'),('10','10am'),('11','11am'),('12','12pm'),('13','1pm'),('14','2pm'),('15','3pm'),('16','4pm'),('17','5pm'),('18','6pm'),('19','7pm'),('20','8pm'),('21','9pm'),('22','10pm'),('23','11pm')])
	isFixed = RadioField('Is the animal fixed?', choices=[('1','Yes'),('0','No')])
	newBreed = SelectField('Breed of animal:', choices=[('Other','Other'),('Domestic Shorthair Mix','Domestic Shorthair Mix'),('Pit Bull Mix','Pit Bull Mix'),('Chihuahua Shorthair Mix' , 'Chihuahua Shorthair Mix'),('Labrador Retriever Mix','Labrador Retriever Mix'),('Domestic Medium Hair Mix','Domestic Medium Hair Mix'),('German Shepherd Mix','German Shepherd Mix'),('Domestic Longhair Mix','Domestic Longhair Mix'),('Siamese Mix','Siamese Mix'),('Australian Cattle Dog Mix' ,'Australian Cattle Dog Mix'),('Dachshund Mix' , 'Dachshund Mix'),('Miniature Poodle Mix' ,'Miniature Poodle Mix'),('Boxer Mix','Boxer Mix'),('Border Collie Mix',' Border Collie Mix'),('Australian Shepherd Mix' , 'Australian Shepherd Mix'),('Rat Terrier Mix' , 'Rat Terrier Mix'),('Catahoula Mix','Catahoula Mix'),('Yorkshire Terrier Mix','Yorkshire Terrier Mix'),('Jack Russell Terrier Mix' , 'Jack Russell Terrier Mix'),('Miniature Schnauzer Mix','Miniature Schnauzer Mix'),('Domestic Shorthair','Domestic Shorthair'),('Siberian Husky Mix','Siberian Husky Mix'),('Chihuahua Longhair Mix',' Chihuahua Longhair Mix'),('Beagle Mix','Beagle Mix'),('Rottweiler Mix','Rottweiler Mix'),('American Bulldog Mix','American Bulldog Mix'),('Shih Tzu Mix','Shih Tzu Mix'),('Chihuahua Shorthair/Dachshund','Chihuahua Shorthair/Dachshund'),('Cairn Terrier Mix','Cairn Terrier Mix'),('Australian Kelpie Mix','Australian Kelpie Mix'),('Great Pyrenees Mix','Great Pyrenees Mix')])
	newColor = SelectField('Color of animal:', choices=[('Other','Other'),('Black/White','Black/White'),('Black','Black'),('Brown Tabby','Brown Tabby'),('Brown Tabby/White','Brown Tabby/White'),('White','White'),('Brown/White','Brown/White'),('Orange Tabby','Orange Tabby'),('Tan/White','Tan/White'),('Tricolor','Tricolor'),('Blue/White','Blue/White'),('Black/Tan','Black/Tan'),('White/Black','White/Black'),('Tan','Tan'),('Brown','Brown'),('White/Brown','White/Brown'),('Tortie','Tortie'),('Calico','Calico'),('Blue','Blue'),('Brown Brindle/White','Brown Brindle/White'),('Orange Tabby/White','Orange Tabby/White'),('Black/Brown','Black/Brown'),('Blue Tabby','Blue Tabby'),('White/Tan','White/Tan'),('Brown/Black','Brown/Black'),('Torbie','Torbie'),('Red/White','Red/White'),('Red','Red'),('Brown Brindle','Brown Brindle'),('Blue Tabby/White','Blue Tabby/White'),('Chocolate/White','Chocolate/White')])