"""users table

Revision ID: 193cd2664cab
Revises: 
Create Date: 2018-03-01 18:17:39.742227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '193cd2664cab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('hasName', sa.String(length=120), nullable=True),
    sa.Column('ageWeeks', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_hasName'), 'user', ['hasName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_hasName'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
